# Generated by Django 4.0 on 2022-01-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_alter_classroom_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='location',
            field=models.CharField(max_length=20, verbose_name='Location'),
        ),
    ]
