# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python39:
      PYTHON_VERSION: '3.9'
  maxParallel: 5

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    architecture: 'x64'

 variables:
 logrocket_env: $(System.DefaultWorkingDirectory)\logrocket_env
 steps:
 - script: $(buildPython.pythonLocation)\python -m pip install --upgrade setuptools virtualenv wheel
 displayName: install python basics
 - script: |
 mkdir $(logrocket_env)
 $(buildPython.pythonLocation)\python -m virtualenv $(logrocket_env)
 displayName: set up the virtual environment
 - script: |
 set Path=$(logrocket_env)\Scripts;%Path%
 echo "We're in a virtual environment!"
 pip install --editable .
 displayName: do things in the virtual environment
 env:
 PYTHON_HOME: ""
 VIRTUAL_ENV: $(logrocket_env)

- task: PythonScript@0
  displayName: 'Export project path'
  inputs:
    scriptSource: 'inline'
    script: |
      """Search all subdirectories for `manage.py`."""
      from glob import iglob
      from os import path
      # Python >= 3.5
      manage_py = next(iglob(path.join('**', 'manage.py'), recursive=True), None)
      if not manage_py:
          raise SystemExit('Could not find a Django project')
      project_location = path.dirname(path.abspath(manage_py))
      print('Found Django project in', project_location)
      print('##vso[task.setvariable variable=projectRoot]{}'.format(project_location))

- script: |
    python -m pip install --upgrade pip setuptools wheel
    pip install -r requirements.txt
    pip install unittest-xml-reporting
  displayName: 'Install prerequisites'

- script: |
    pushd '$(projectRoot)'
    python manage.py test --testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner --no-input
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: "**/TEST-*.xml"
    testRunTitle: 'Python $(PYTHON_VERSION)'
  condition: succeededOrFailed()
